/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FLIGHT_EVENT, flight_event_t, AUTO)


PB_BIND(ACKNOWLEDGE, acknowledge_t, AUTO)


PB_BIND(PRESSURE_READING, pressure_reading_t, AUTO)


PB_BIND(IMU_READING, imu_reading_t, AUTO)


PB_BIND(STATE_ESTIMATE, state_estimate_t, AUTO)


PB_BIND(CAN_BUS, can_bus_t, AUTO)


PB_BIND(PYRO_STATUS, pyro_status_t, AUTO)


PB_BIND(CAN_LOKI_TO_FJALAR, can_loki_to_fjalar_t, AUTO)


PB_BIND(CAN_FJALAR_TO_LOKI, can_fjalar_to_loki_t, AUTO)


PB_BIND(CAN_SIGURD_TO_FJALAR, can_sigurd_to_fjalar_t, AUTO)


PB_BIND(CAN_FJALAR_TO_SIGURD, can_fjalar_to_sigurd_t, AUTO)


PB_BIND(CAN_FAFNIR_TO_FJALAR, can_fafnir_to_fjalar_t, AUTO)


PB_BIND(CAN_FJALAR_TO_FAFNIR, can_fjalar_to_fafnir_t, AUTO)


PB_BIND(LORA_GCB_TO_FJALAR, lora_gcb_to_fjalar_t, AUTO)


PB_BIND(LORA_FJALAR_TO_GCB, lora_fjalar_to_gcb_t, AUTO)


PB_BIND(FJALAR_INFO, fjalar_info_t, AUTO)


PB_BIND(GNSS_POSITION, gnss_position_t, AUTO)


PB_BIND(GNSS_STATUS, gnss_status_t, AUTO)


PB_BIND(SET_SUDO, set_sudo_t, AUTO)


PB_BIND(CLEAR_FLASH, clear_flash_t, AUTO)


PB_BIND(READ_FLASH, read_flash_t, AUTO)


PB_BIND(FLASH_DATA, flash_data_t, AUTO)


PB_BIND(READY_UP, ready_up_t, AUTO)


PB_BIND(ENTER_IDLE, enter_idle_t, AUTO)


PB_BIND(TRIGGER_PYRO, trigger_pyro_t, AUTO)


PB_BIND(HIL_IN, hil_in_t, AUTO)


PB_BIND(HIL_OUT, hil_out_t, AUTO)


PB_BIND(FJALAR_DATA, fjalar_data_t, AUTO)


PB_BIND(FJALAR_MESSAGE, fjalar_message_t, AUTO)





